<h1>The XOR Problem</h1>
<br>
<p>It is the problem of using a neural network to predict the outputs of XOR logic gates given two binary inputs. An XOR function should return a true value if the two inputs are not equal and a false value if they are equal.</p>
<img src="img/xor1.png">

In [1]:
import numpy as np

arr_in = np.array([[0,0],[0,1],[1,0],[1,1]])
arr_out = np.array([[0],[1],[1],[0]])
lr = 0.1

# initialize the weights with random values
inp_layer, hidden_layer, out_layer = 2, 2, 1
hidden_weights = np.random.uniform(size=(inp_layer,hidden_layer))
hidden_bias = np.random.uniform(size=(1,hidden_layer))
out_weights = np.random.uniform(size=(hidden_layer, out_layer))
out_bias = np.random.uniform(size=(1,out_layer))

print(hidden_weights, hidden_bias, '\n\n', out_weights, out_bias)

[[0.99919912 0.98657075]
 [0.81295181 0.5156983 ]] [[0.85921135 0.58230564]] 

 [[0.75126609]
 [0.29772291]] [[0.68637994]]


In [2]:
def sigmoid(x):
    return 1/(1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

In [3]:
#Training algorithm
a = 1
for _ in range(100000):
    #Forward Propagation
    hidden_layer_activation = np.dot(arr_in, hidden_weights) + hidden_bias
    hidden_layer_out = sigmoid(hidden_layer_activation)
    out_layer_activation = np.dot(hidden_layer_out, out_weights) + out_bias
    predicted_out = sigmoid(out_layer_activation)
    if a==1:
        print('Before Prediction:\n', predicted_out,'\n\n')
        a+=1
    #Backpropagation
    error = arr_out - predicted_out
    d_predicted_out = error * sigmoid_derivative(predicted_out)  
    error_hidden_layer = d_predicted_out.dot(out_weights.T)
    d_hidden_layer = error_hidden_layer * sigmoid_derivative(hidden_layer_out)
    #Updating Weights and Biases
    
    out_weights += hidden_layer_out.T.dot(d_predicted_out) * lr
    out_bias += np.sum(d_predicted_out,axis=0,keepdims=True) * lr
    hidden_weights += arr_in.T.dot(d_hidden_layer) * lr
    hidden_bias += np.sum(d_hidden_layer,axis=0,keepdims=True) * lr
print('Final Prediction:\n', predicted_out)

Before Prediction:
 [[0.80300136]
 [0.82377009]
 [0.82958817]
 [0.8394099 ]] 


Final Prediction:
 [[0.01296968]
 [0.98890008]
 [0.98894365]
 [0.01140276]]
